[project]
name = "splatter-vae"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cython<3",
    "einops>=0.8.1",
    "gsplat",
    "numpy<2.0.0",
    "opencv-python>=4.11.0.86",
    "pyyaml>=6.0.3",
    "robomimic",
    "robosuite==1.4.1",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "wandb>=0.23.1",
    "mimicgen",
    "mujoco==2.3.2",
    "gradio>=4.44.1",
    "scikit-learn>=1.7.2",
]
[tool.uv.extra-build-dependencies]
gsplat = ["torch"]

[tool.uv.sources]
gsplat = { git = "https://github.com/nerfstudio-project/gsplat.git" }
robomimic = { path = "dataset/robomimic", editable = true }
mimicgen = { path = "dataset/mimicgen", editable = true }
